<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Async Await</title>
  <link rel="stylesheet" href="../base.css">
</head>

<body>
  <script>
    function wait(ms = 0) {
      return new Promise((resolve) => {
        setTimeout(resolve, ms);
      });
    }

    function makePizza(toppings = []) {
      return new Promise((resolve, reject) => {
        // reject if people try with pineapple
        if (toppings.includes('pineapple')) {
          reject('Seriously? Get out üçç');
        }
        const amountOfTimeToBake = 500 + toppings.length * 200;
        // wait 1 second for the pizza to cook:
        setTimeout(() => {
          // when you are ready, you can resolve this promise
          resolve(`Here is your pizza üçï with the toppings ${toppings.join(' ')}`);
        }, amountOfTimeToBake);
        // if something went wrong, we can reject this promise;
      });
    }

    // Try catch method
    // async function go() {
    //   try {
    //     const pizza = makePizza(['pineapple']);
    //     console.log(pizza);
    //   } catch (err) {
    //     console.log('Ohhh noo!');
    //     console.log(err);
    //   }
    // }

    // Handle error
    function handleError(err) {
      console.log('Ohhh noooo!');
      console.log(err);
    }

    async function go() {
      const pizza = await makePizza(['pineapple']);
      console.log(pizza);
      return pizza;
    }

    // Catch it at run time
    // go().catch(handleError);

    // Make a safe function with a Higher Order Function
    function makeSafe(fn, errorHandler) {
      return function () {
        fn().catch(errorHandler);
      };
    }

    const safeGo = makeSafe(go, handleError);

    safeGo();
  </script>
</body>

</html>